pipeline {
    agent any

    environment {
        MONGO_DB_URI = 'mongodb://localhost:27017/recovery-db'
        JENKINS_PROCESS_API_URL = 'http://localhost:8090/recovery-process-pipeline/job/process-recovery-system/build'
        JENKINS_AUTH = '11316aec32abeb92629dc71a3631310dc'
        JENKINS_CRUMB = '7adc92971ffaf7bf783c247134b82788a6253683c614a2cd5cf476926e1c9f06'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Config app') {
            steps {
                script {
                    dir("recovery-system") {
                        def envVars = [
                            "MONGO_DB_URI=${env.MONGO_DB_URI}",
                            "JENKINS_PROCESS_API_URL=${env.JENKINS_PROCESS_API_URL}",
                            "JENKINS_AUTH=${env.JENKINS_AUTH}",
                            "JENKINS_CRUMB=${env.JENKINS_CRUMB}"
                        ]

                        // Write env vars to a file
                        writeFile file: '.env', text: envVars.join("\n")

                        // Verify the .env file is created
                        sh 'cat .env'
                    }

                }
            }
        }

        stage('Build and Deploy') {
            steps {
                dir("recovery-system") {
                    script {
                        def networkExists = sh(script: 'docker network ls --filter name=shared_network -q', returnStdout: true).trim()

                        if (!networkExists) {
                            sh 'docker network create shared_network'
                        }

                        sh 'docker-compose up -d --build'

                        sh 'docker push mohamedakenouch/recovery-system/recovery-app:latest'

                    }

                }

            }
        }
    }
}